//------------------------------------------------------------------------------
/*
 * Title: FANN C# NetworkType enumerator
 */

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

namespace FANNCSharp
{
    /* Enum: NetworkType

        Definition of network types used by <FANNCSharp.Float::NeuralNet::NetworkType>

        LAYER - Each layer only has connections to the next layer
        SHORTCUT - Each layer has connections to all following layers

       See Also:
          <FANNCSharp.Float::NeuralNet::NetworkType>, <fann_get_network_type at http://libfann.github.io/fann/docs/files/fann-h.html#fann_get_network_type>

       This enumeration appears in FANN >= 2.1.0
    */
    public enum NetworkType
    {
        LAYER = 0,
        SHORTCUT
    }

}
