//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperFixed {

internal class fannfixed {
  public static SWIGTYPE_p_FILE fopen(string filename, string mode) {
    global::System.IntPtr cPtr = fannfixedPINVOKE.fopen(filename, mode);
    SWIGTYPE_p_FILE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FILE(cPtr, false);
    return ret;
  }

  public static int fclose(SWIGTYPE_p_FILE stream) {
    int ret = fannfixedPINVOKE.fclose(SWIGTYPE_p_FILE.getCPtr(stream));
    return ret;
  }

  public static readonly string FANNPRINTF = fannfixedPINVOKE.FANNPRINTF_get();
  public static readonly string FANNSCANF = fannfixedPINVOKE.FANNSCANF_get();
}

}
