//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperDouble {

internal class doubleVectorVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<doubleVector>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal doubleVectorVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(doubleVectorVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~doubleVectorVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fanndoublePINVOKE.delete_doubleVectorVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public doubleVectorVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (doubleVector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public doubleVector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(doubleVector[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(doubleVector[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, doubleVector[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<doubleVector> global::System.Collections.Generic.IEnumerable<doubleVector>.GetEnumerator() {
    return new doubleVectorVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new doubleVectorVectorEnumerator(this);
  }

  public doubleVectorVectorEnumerator GetEnumerator() {
    return new doubleVectorVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class doubleVectorVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<doubleVector>
  {
    private doubleVectorVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public doubleVectorVectorEnumerator(doubleVectorVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public doubleVector Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (doubleVector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    fanndoublePINVOKE.doubleVectorVector_Clear(swigCPtr);
  }

  public void Add(doubleVector x) {
    fanndoublePINVOKE.doubleVectorVector_Add(swigCPtr, doubleVector.getCPtr(x));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = fanndoublePINVOKE.doubleVectorVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = fanndoublePINVOKE.doubleVectorVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    fanndoublePINVOKE.doubleVectorVector_reserve(swigCPtr, n);
  }

  public doubleVectorVector() : this(fanndoublePINVOKE.new_doubleVectorVector__SWIG_0(), true) {
  }

  public doubleVectorVector(doubleVectorVector other) : this(fanndoublePINVOKE.new_doubleVectorVector__SWIG_1(doubleVectorVector.getCPtr(other)), true) {
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public doubleVectorVector(int capacity) : this(fanndoublePINVOKE.new_doubleVectorVector__SWIG_2(capacity), true) {
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  private doubleVector getitemcopy(int index) {
    doubleVector ret = new doubleVector(fanndoublePINVOKE.doubleVectorVector_getitemcopy(swigCPtr, index), true);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private doubleVector getitem(int index) {
    doubleVector ret = new doubleVector(fanndoublePINVOKE.doubleVectorVector_getitem(swigCPtr, index), false);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, doubleVector val) {
    fanndoublePINVOKE.doubleVectorVector_setitem(swigCPtr, index, doubleVector.getCPtr(val));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(doubleVectorVector values) {
    fanndoublePINVOKE.doubleVectorVector_AddRange(swigCPtr, doubleVectorVector.getCPtr(values));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public doubleVectorVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = fanndoublePINVOKE.doubleVectorVector_GetRange(swigCPtr, index, count);
    doubleVectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new doubleVectorVector(cPtr, true);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, doubleVector x) {
    fanndoublePINVOKE.doubleVectorVector_Insert(swigCPtr, index, doubleVector.getCPtr(x));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, doubleVectorVector values) {
    fanndoublePINVOKE.doubleVectorVector_InsertRange(swigCPtr, index, doubleVectorVector.getCPtr(values));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    fanndoublePINVOKE.doubleVectorVector_RemoveAt(swigCPtr, index);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    fanndoublePINVOKE.doubleVectorVector_RemoveRange(swigCPtr, index, count);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public static doubleVectorVector Repeat(doubleVector value, int count) {
    global::System.IntPtr cPtr = fanndoublePINVOKE.doubleVectorVector_Repeat(doubleVector.getCPtr(value), count);
    doubleVectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new doubleVectorVector(cPtr, true);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    fanndoublePINVOKE.doubleVectorVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    fanndoublePINVOKE.doubleVectorVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, doubleVectorVector values) {
    fanndoublePINVOKE.doubleVectorVector_SetRange(swigCPtr, index, doubleVectorVector.getCPtr(values));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
