//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperDouble {

internal class doubleVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<double>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal doubleVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(doubleVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~doubleVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fanndoublePINVOKE.delete_doubleVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public doubleVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (double element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public double this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(double[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(double[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, double[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<double> global::System.Collections.Generic.IEnumerable<double>.GetEnumerator() {
    return new doubleVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new doubleVectorEnumerator(this);
  }

  public doubleVectorEnumerator GetEnumerator() {
    return new doubleVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class doubleVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<double>
  {
    private doubleVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public doubleVectorEnumerator(doubleVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public double Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (double)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    fanndoublePINVOKE.doubleVector_Clear(swigCPtr);
  }

  public void Add(double x) {
    fanndoublePINVOKE.doubleVector_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = fanndoublePINVOKE.doubleVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = fanndoublePINVOKE.doubleVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    fanndoublePINVOKE.doubleVector_reserve(swigCPtr, n);
  }

  public doubleVector() : this(fanndoublePINVOKE.new_doubleVector__SWIG_0(), true) {
  }

  public doubleVector(doubleVector other) : this(fanndoublePINVOKE.new_doubleVector__SWIG_1(doubleVector.getCPtr(other)), true) {
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public doubleVector(int capacity) : this(fanndoublePINVOKE.new_doubleVector__SWIG_2(capacity), true) {
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  private double getitemcopy(int index) {
    double ret = fanndoublePINVOKE.doubleVector_getitemcopy(swigCPtr, index);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private double getitem(int index) {
    double ret = fanndoublePINVOKE.doubleVector_getitem(swigCPtr, index);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, double val) {
    fanndoublePINVOKE.doubleVector_setitem(swigCPtr, index, val);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(doubleVector values) {
    fanndoublePINVOKE.doubleVector_AddRange(swigCPtr, doubleVector.getCPtr(values));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public doubleVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = fanndoublePINVOKE.doubleVector_GetRange(swigCPtr, index, count);
    doubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new doubleVector(cPtr, true);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, double x) {
    fanndoublePINVOKE.doubleVector_Insert(swigCPtr, index, x);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, doubleVector values) {
    fanndoublePINVOKE.doubleVector_InsertRange(swigCPtr, index, doubleVector.getCPtr(values));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    fanndoublePINVOKE.doubleVector_RemoveAt(swigCPtr, index);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    fanndoublePINVOKE.doubleVector_RemoveRange(swigCPtr, index, count);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public static doubleVector Repeat(double value, int count) {
    global::System.IntPtr cPtr = fanndoublePINVOKE.doubleVector_Repeat(value, count);
    doubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new doubleVector(cPtr, true);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    fanndoublePINVOKE.doubleVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    fanndoublePINVOKE.doubleVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, doubleVector values) {
    fanndoublePINVOKE.doubleVector_SetRange(swigCPtr, index, doubleVector.getCPtr(values));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(double value) {
    bool ret = fanndoublePINVOKE.doubleVector_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(double value) {
    int ret = fanndoublePINVOKE.doubleVector_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(double value) {
    int ret = fanndoublePINVOKE.doubleVector_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(double value) {
    bool ret = fanndoublePINVOKE.doubleVector_Remove(swigCPtr, value);
    return ret;
  }

}

}
