//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperDouble {

internal class ConnectionArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConnectionArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConnectionArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ConnectionArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fanndoublePINVOKE.delete_ConnectionArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ConnectionArray(int nelements) : this(fanndoublePINVOKE.new_ConnectionArray(nelements), true) {
  }

  public Connection getitem(int index) {
    Connection ret = new Connection(fanndoublePINVOKE.ConnectionArray_getitem(swigCPtr, index), true);
    return ret;
  }

  public void setitem(int index, Connection value) {
    fanndoublePINVOKE.ConnectionArray_setitem(swigCPtr, index, Connection.getCPtr(value));
    if (fanndoublePINVOKE.SWIGPendingException.Pending) throw fanndoublePINVOKE.SWIGPendingException.Retrieve();
  }

  public Connection cast() {
    global::System.IntPtr cPtr = fanndoublePINVOKE.ConnectionArray_cast(swigCPtr);
    Connection ret = (cPtr == global::System.IntPtr.Zero) ? null : new Connection(cPtr, false);
    return ret;
  }

  public static ConnectionArray frompointer(Connection t) {
    global::System.IntPtr cPtr = fanndoublePINVOKE.ConnectionArray_frompointer(Connection.getCPtr(t));
    ConnectionArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new ConnectionArray(cPtr, false);
    return ret;
  }

}

}
