//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperDouble {

internal class doubleArrayArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal doubleArrayArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(doubleArrayArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~doubleArrayArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fanndoublePINVOKE.delete_doubleArrayArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public doubleArrayArray(int nelements) : this(fanndoublePINVOKE.new_doubleArrayArray(nelements), true) {
  }

  public SWIGTYPE_p_double getitem(int index) {
    global::System.IntPtr cPtr = fanndoublePINVOKE.doubleArrayArray_getitem(swigCPtr, index);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public void setitem(int index, SWIGTYPE_p_double value) {
    fanndoublePINVOKE.doubleArrayArray_setitem(swigCPtr, index, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_p_double cast() {
    global::System.IntPtr cPtr = fanndoublePINVOKE.doubleArrayArray_cast(swigCPtr);
    SWIGTYPE_p_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_double(cPtr, false);
    return ret;
  }

  public static doubleArrayArray frompointer(SWIGTYPE_p_p_double t) {
    global::System.IntPtr cPtr = fanndoublePINVOKE.doubleArrayArray_frompointer(SWIGTYPE_p_p_double.getCPtr(t));
    doubleArrayArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new doubleArrayArray(cPtr, false);
    return ret;
  }

}

}
