//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperFloat {

internal class floatVectorVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<floatVector>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal floatVectorVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(floatVectorVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~floatVectorVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fannfloatPINVOKE.delete_floatVectorVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public floatVectorVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (floatVector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public floatVector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(floatVector[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(floatVector[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, floatVector[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<floatVector> global::System.Collections.Generic.IEnumerable<floatVector>.GetEnumerator() {
    return new floatVectorVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new floatVectorVectorEnumerator(this);
  }

  public floatVectorVectorEnumerator GetEnumerator() {
    return new floatVectorVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class floatVectorVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<floatVector>
  {
    private floatVectorVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public floatVectorVectorEnumerator(floatVectorVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public floatVector Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (floatVector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    fannfloatPINVOKE.floatVectorVector_Clear(swigCPtr);
  }

  public void Add(floatVector x) {
    fannfloatPINVOKE.floatVectorVector_Add(swigCPtr, floatVector.getCPtr(x));
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = fannfloatPINVOKE.floatVectorVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = fannfloatPINVOKE.floatVectorVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    fannfloatPINVOKE.floatVectorVector_reserve(swigCPtr, n);
  }

  public floatVectorVector() : this(fannfloatPINVOKE.new_floatVectorVector__SWIG_0(), true) {
  }

  public floatVectorVector(floatVectorVector other) : this(fannfloatPINVOKE.new_floatVectorVector__SWIG_1(floatVectorVector.getCPtr(other)), true) {
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public floatVectorVector(int capacity) : this(fannfloatPINVOKE.new_floatVectorVector__SWIG_2(capacity), true) {
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  private floatVector getitemcopy(int index) {
    floatVector ret = new floatVector(fannfloatPINVOKE.floatVectorVector_getitemcopy(swigCPtr, index), true);
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private floatVector getitem(int index) {
    floatVector ret = new floatVector(fannfloatPINVOKE.floatVectorVector_getitem(swigCPtr, index), false);
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, floatVector val) {
    fannfloatPINVOKE.floatVectorVector_setitem(swigCPtr, index, floatVector.getCPtr(val));
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(floatVectorVector values) {
    fannfloatPINVOKE.floatVectorVector_AddRange(swigCPtr, floatVectorVector.getCPtr(values));
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public floatVectorVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = fannfloatPINVOKE.floatVectorVector_GetRange(swigCPtr, index, count);
    floatVectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new floatVectorVector(cPtr, true);
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, floatVector x) {
    fannfloatPINVOKE.floatVectorVector_Insert(swigCPtr, index, floatVector.getCPtr(x));
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, floatVectorVector values) {
    fannfloatPINVOKE.floatVectorVector_InsertRange(swigCPtr, index, floatVectorVector.getCPtr(values));
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    fannfloatPINVOKE.floatVectorVector_RemoveAt(swigCPtr, index);
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    fannfloatPINVOKE.floatVectorVector_RemoveRange(swigCPtr, index, count);
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public static floatVectorVector Repeat(floatVector value, int count) {
    global::System.IntPtr cPtr = fannfloatPINVOKE.floatVectorVector_Repeat(floatVector.getCPtr(value), count);
    floatVectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new floatVectorVector(cPtr, true);
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    fannfloatPINVOKE.floatVectorVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    fannfloatPINVOKE.floatVectorVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, floatVectorVector values) {
    fannfloatPINVOKE.floatVectorVector_SetRange(swigCPtr, index, floatVectorVector.getCPtr(values));
    if (fannfloatPINVOKE.SWIGPendingException.Pending) throw fannfloatPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
