//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperFloat {

internal class floatArrayArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal floatArrayArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(floatArrayArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~floatArrayArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fannfloatPINVOKE.delete_floatArrayArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public floatArrayArray(int nelements) : this(fannfloatPINVOKE.new_floatArrayArray(nelements), true) {
  }

  public SWIGTYPE_p_float getitem(int index) {
    global::System.IntPtr cPtr = fannfloatPINVOKE.floatArrayArray_getitem(swigCPtr, index);
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

  public void setitem(int index, SWIGTYPE_p_float value) {
    fannfloatPINVOKE.floatArrayArray_setitem(swigCPtr, index, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_p_float cast() {
    global::System.IntPtr cPtr = fannfloatPINVOKE.floatArrayArray_cast(swigCPtr);
    SWIGTYPE_p_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_float(cPtr, false);
    return ret;
  }

  public static floatArrayArray frompointer(SWIGTYPE_p_p_float t) {
    global::System.IntPtr cPtr = fannfloatPINVOKE.floatArrayArray_frompointer(SWIGTYPE_p_p_float.getCPtr(t));
    floatArrayArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new floatArrayArray(cPtr, false);
    return ret;
  }

}

}
